# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory
WORKDIR /koboldcpp

# Install git
RUN apt-get update && apt-get install -y git build-essential
RUN apt-get update && apt-get install -y libopenblas-dev
RUN git clone https://github.com/LostRuins/koboldcpp.git --branch v1.43 ./
RUN pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt

# ENV NOAVX2_BUILD=1
ENV LLAMA_OPENBLAS=1
RUN make

RUN apt-get clean s&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Make port 80 available to the world outside this container
EXPOSE 80

# Use koboldcpp.py as the entrypoint when the container launches
ENTRYPOINT ["python", "koboldcpp.py"]

